services:
  db-manager:
    build: 
      context: .
      args:
        - DNS=8.8.8.8
    image: hbdb-main
    container_name: hbdb-manager
    restart: always
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
